### ISSUE TITLE
Error when running asari on Version 0.6

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li/asari#4]
Good morning Shuzhao,

I encountered an error when running the standard samples using asari v 0.6. Let me know if you know whether that is systematic error or due to the way I run the samples.
```
python3 -m asari.main neg /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/
Determination of memory status is not supported on this 
 platform, measuring for memoryleaks will never fail


~~~~~~~ Hello from Asari! ~~~~~~~~~


Working on  /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/
extracted 1537538 valide data points.

Processing /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/WBJ4_10uM_Qstd_20211223_002.mzML, found 9760 mass traces.
Detected 10618 good peaks.
    (mass_accuracy, stdev in matched results) = (-0.01,  3.31 ) ppm.
extracted 1561140 valide data points.

Processing /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/DL8_10uM_Qstd_20211223_002.mzML, found 10115 mass traces.
Detected 11053 good peaks.
    (mass_accuracy, stdev in matched results) = (-0.08,  3.17 ) ppm.
extracted 1649054 valide data points.

Processing /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/LWB12_20uM_20211223_002.mzML, found 7723 mass traces.
Detected 9611 good peaks.
    (mass_accuracy, stdev in matched results) = (-0.07,  3.30 ) ppm.

[@.@] Anchoring with 6193 initial formula matches.
[@.@] Initial estimation done on
/Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/WBJ4_10uM_Qstd_20211223_002.mzML
/Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/DL8_10uM_Qstd_20211223_002.mzML
/Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/LWB12_20uM_20211223_002.mzML
extracted 1539235 valide data points.


...



Processing /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/T9_20uM_20211223_002.mzML, found 7612 mass traces.
Detected 8410 good peaks.
    (mass_accuracy, stdev in matched results) = (-0.20,  3.50 ) ppm.
extracted 1566410 valide data points.

Processing /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/KWB8_20uM_20211223_002.mzML, found 7504 mass traces.
Detected 9355 good peaks.
    (mass_accuracy, stdev in matched results) = (-0.09,  3.44 ) ppm.
extracted 1562261 valide data points.

Processing /Users/gongm/Documents/projects/Authentic_Standard/raw_data/Authentic_Compound/20211223_HILICpos_RPneg_mzML/RPneg/T9_10uM_Qstd_20211223_002.mzML, found 9716 mass traces.
Detected 10454 good peaks.
    (mass_accuracy, stdev in matched results) = (-0.14,  3.36 ) ppm.
Traceback (most recent call last):
  File "/Users/gongm/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/gongm/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/gongm/Documents/projects/Emory-U2C/tool/asari/asari/main.py", line 25, in <module>
    main(directory)
  File "/Users/gongm/Documents/projects/Emory-U2C/tool/asari/asari/main.py", line 15, in main
    process_project(
  File "/Users/gongm/Documents/projects/Emory-U2C/tool/asari/asari/lcms_experiment.py", line 83, in process_project
    EE.process_all()
  File "/Users/gongm/Documents/projects/Emory-U2C/tool/asari/asari/lcms_experiment.py", line 139, in process_all
    self.correspondence()
  File "/Users/gongm/Documents/projects/Emory-U2C/tool/asari/asari/lcms_experiment.py", line 296, in correspondence
    FeatureList = peaks_to_features(peak_dict, self.parameters['rtime_tolerance'], self.ordered_sample_names)
  File "/Users/gongm/Documents/projects/Emory-U2C/tool/asari/asari/utils.py", line 116, in peaks_to_features
    for F in __bin_by_median_rt__(v, rtime_tolerance):
  File "/Users/gongm/Documents/projects/Emory-U2C/tool/asari/asari/utils.py", line 111, in __bin_by_median_rt__
    List_of_tuples.sort()
TypeError: '<' not supported between instances of 'ext_Peak' and 'ext_Peak'
```

Thanks very much! I will consult Amnah as well. Happy New year and good wishes for the productive year of 2022.

Best,
Minghao Gong

**Comment by shuzhao-li** [comment]
That was a tie in RT comparison but overcome in newer version.
