### ISSUE TITLE
sample tracking error

### ISSUE THREAD

**Issue by shuzhao-li** [shuzhao-li/asari#8]
➜  20220321-Ecoli-Shujian asari process --input HILICneg --out ecoli_cre_hilicneg --mode neg

~~~~~~~ Hello from Asari (1.4.2) ~~~~~~~~~

Working on ~~ HILICneg ~~ 


Processed 12C_Ecoli_20220321_003_20220322094510.mzML with 3708 mass tracks.
Processed 12C_Ecoli_20220321_003_20220322125715.mzML with 3777 mass tracks.
Processed 12C_Ecoli_20220321_003.mzML with 3467 mass tracks.
Processed 12C_Ecoli_QRESS_20220321_003.mzML with 3897 mass tracks.
Processed 12C_Ecoli_QRESS_20220321_003_20220322102750.mzML with 4098 mass tracks.
Processed 12C_Ecoli_QRESS_20220321_003_20220322133956.mzML with 4057 mass tracks.
[Warning] Not index found and build_index_from_scratch is False
mzML processing error in sample HILICneg/13C_Ecoli_QRESS_20220321_003.mzML, skipped.
Processed 13C_Ecoli_20220321_003.mzML with 3656 mass tracks.
Processed 13C_Ecoli_20220321_003_20220322100630.mzML with 3948 mass tracks.
Processed 13C_Ecoli_QRESS_20220321_003_20220322104911.mzML with 4173 mass tracks.
Processed 13C_Ecoli_20220321_003_20220322131835.mzML with 3968 mass tracks.
Processed 13C_Ecoli_QRESS_20220321_003_20220322140116.mzML with 4336 mass tracks.

Initiating MassGrid, ...
    The reference sample is:
    ||* 13C_Ecoli_QRESS_20220321_003_20220322140116 *||

Max _retention_time is 299.84 at scan number 1095.

Traceback (most recent call last):
  File "/Users/shuzhao/.pyenv/versions/3.7.4/bin/asari", line 8, in <module>
    sys.exit(main())
  File "/Users/shuzhao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/asari/main.py", line 82, in main
    process_project( list_input_files,  parameters )        #directory = args.input
  File "/Users/shuzhao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/asari/workflow.py", line 62, in process_project
    EE.process_all()
  File "/Users/shuzhao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/asari/experiment.py", line 73, in process_all
    self.CMAP.construct_mass_grid()
  File "/Users/shuzhao/.pyenv/versions/3.7.4/lib/python3.7/site-packages/asari/constructors.py", line 85, in construct_mass_grid
    sample_ids.pop(self.experiment.reference_sample_id)
IndexError: pop index out of range

**Comment by shuzhao-li** [comment]
Likely overwritten this bug already.
